package dev.mando;
import org.bukkit.Bukkit;import org.bukkit.command.CommandSender;
import java.io.*;import java.nio.charset.StandardCharsets;import java.nio.file.*;import java.time.*;import java.time.format.DateTimeFormatter;import java.util.*;import java.util.zip.*;
public final class AdminOperations {
 private final Mando plugin;private final PlayerStorage storage;private final ModuleManager modules;private final PlatformDetector platform;private final IntegrationManager integrations;private final Path log;
 public AdminOperations(Mando p,PlayerStorage s,ModuleManager m,PlatformDetector pf,IntegrationManager i){plugin=p;storage=s;modules=m;platform=pf;integrations=i;log=p.getDataFolder().toPath().resolve("logs/mando.log");}
 public void log(String cat,String msg){try{Files.createDirectories(log.getParent());String line=Instant.now()+" ["+cat.toUpperCase(Locale.ROOT)+"] "+msg+System.lineSeparator();Files.writeString(log,line,StandardCharsets.UTF_8,StandardOpenOption.CREATE,StandardOpenOption.APPEND);}catch(IOException e){plugin.getLogger().warning("mando.log: "+e.getMessage());}if(plugin.getConfig().getBoolean("admin.debug",false))plugin.getLogger().info("["+cat+"] "+msg);}
 public String status(){return "Mando "+plugin.getPluginMeta().getVersion()+" | "+platform.platform()+" | jugadores="+Bukkit.getOnlinePlayers().size()+" | "+integrations.summary()+" | debug="+plugin.getConfig().getBoolean("admin.debug",false);}
 public void backup(CommandSender s){storage.flushAll();storage.backupAll("admin");log("backup","Backup solicitado por "+s.getName());s.sendMessage("Mando: backup estricto completado.");}
 public Path diagnose(CommandSender s)throws IOException{Path out=plugin.getDataFolder().toPath().resolve("diagnostics");Files.createDirectories(out);Path zip=out.resolve("mando-diagnostic-"+DateTimeFormatter.ofPattern("yyyyMMdd-HHmmss").format(LocalDateTime.now())+".zip");try(ZipOutputStream z=new ZipOutputStream(Files.newOutputStream(zip))){entry(z,"status.txt",status()+"\nJava="+System.getProperty("java.version")+"\n");entry(z,"config-summary.txt","language="+plugin.getConfig().getString("language","es")+"\nsetup.completed="+plugin.getConfig().getBoolean("setup.completed")+"\nmodules.homes="+modules.enabled("homes")+"\nmodules.warps="+modules.enabled("warps")+"\nmodules.mail="+modules.enabled("mail")+"\nmodules.tpa="+modules.enabled("tpa")+"\n");if(Files.exists(log))entry(z,"mando.log",Files.readString(log));}log("diagnose","ZIP creado por "+s.getName()+": "+zip.getFileName());return zip;}
 private void entry(ZipOutputStream z,String name,String text)throws IOException{z.putNextEntry(new ZipEntry(name));z.write(text.getBytes(StandardCharsets.UTF_8));z.closeEntry();}
 public boolean confirm(String token){return token!=null&&token.equalsIgnoreCase("CONFIRM");}
 public void shutdown(CommandSender s,boolean restart){log("critical",(restart?"restart":"shutdown")+" solicitado por "+s.getName());storage.flushAll();storage.backupAll(restart?"restart":"shutdown");if(restart)Bukkit.dispatchCommand(Bukkit.getConsoleSender(),"restart");else Bukkit.shutdown();}
}
