package dev.mando;
import net.kyori.adventure.bossbar.BossBar;import net.kyori.adventure.text.*;import net.kyori.adventure.text.minimessage.MiniMessage;import net.kyori.adventure.title.Title;import org.bukkit.*;import org.bukkit.command.*;import org.bukkit.entity.Player;import org.bukkit.scheduler.BukkitTask;import java.util.*;
public final class AnnouncementManager implements CommandExecutor,TabCompleter{
 private final MandoPlugin plugin;private final MiniMessage mm=MiniMessage.miniMessage();private BukkitTask rotation,bossTask;private BossBar boss;private int index;private boolean paused;private String finishCommand;
 public AnnouncementManager(MandoPlugin p){plugin=p;}
 public void start(){stopRotation();paused=false;if(!plugin.getConfig().getBoolean("announcements.enabled",false))return;List<String> list=plugin.getConfig().getStringList("announcements.messages");if(list.isEmpty())return;long sec=Math.max(10,plugin.getConfig().getLong("announcements.interval-seconds",300));rotation=Bukkit.getScheduler().runTaskTimer(plugin,()->{if(paused)return;String raw=list.get(index++%list.size());int cut=raw.indexOf('|');String type=cut>0?raw.substring(0,cut):"CHAT",msg=cut>0?raw.substring(cut+1):raw;send(type,msg,plugin.getConfig().getInt("announcements.bossbar-seconds",10));},sec*20L,sec*20L);}
 private void stopRotation(){if(rotation!=null){rotation.cancel();rotation=null;}}
 public void send(String type,String raw,int seconds){Component c=mm.deserialize(raw);switch(type.toUpperCase(Locale.ROOT)){case "ACTIONBAR"->Bukkit.getOnlinePlayers().forEach(p->p.sendActionBar(c));case "TITLE"->Bukkit.getOnlinePlayers().forEach(p->p.showTitle(Title.title(c,Component.empty())));case "SUBTITLE"->Bukkit.getOnlinePlayers().forEach(p->p.showTitle(Title.title(Component.empty(),c)));case "BOSSBAR"->showBoss(c,seconds);default->Bukkit.getOnlinePlayers().forEach(p->p.sendMessage(c));}}
 private void showBoss(Component c,int seconds){stopBoss();finishCommand=plugin.getConfig().getString("announcements.bossbar-finish-command","");boss=BossBar.bossBar(c,1f,BossBar.Color.PURPLE,BossBar.Overlay.PROGRESS);Bukkit.getOnlinePlayers().forEach(p->p.showBossBar(boss));int total=Math.max(1,seconds);final int[] left={total};bossTask=Bukkit.getScheduler().runTaskTimer(plugin,()->{left[0]--;if(left[0]<=0){String cmd=finishCommand;stopBoss();if(cmd!=null&&!cmd.isBlank())Bukkit.dispatchCommand(Bukkit.getConsoleSender(),cmd);return;}boss.progress(Math.max(0.01f,left[0]/(float)total));},20L,20L);}
 public void stopBoss(){finishCommand=null;if(bossTask!=null){bossTask.cancel();bossTask=null;}if(boss!=null){BossBar b=boss;Bukkit.getOnlinePlayers().forEach(p->p.hideBossBar(b));boss=null;}}
 public boolean onCommand(CommandSender s,Command c,String l,String[] a){if(a.length==0){s.sendMessage("/announce <chat|actionbar|title|subtitle|bossbar> <mensaje> | /announce stop");return true;}if(a[0].equalsIgnoreCase("stop")){stopBoss();s.sendMessage("Mando: anuncio detenido.");return true;}if(a[0].equalsIgnoreCase("pause")){paused=true;s.sendMessage("Mando: rotación de anuncios pausada.");return true;}if(a[0].equalsIgnoreCase("resume")){paused=false;s.sendMessage("Mando: rotación de anuncios reanudada.");return true;}if(a[0].equalsIgnoreCase("list")){List<String> list=plugin.getConfig().getStringList("announcements.messages");s.sendMessage("Mando: "+list.size()+" anuncios configurados"+(paused?" · pausados":"")+".");for(int i=0;i<list.size();i++)s.sendMessage((i+1)+". "+list.get(i));return true;}if(a.length<2)return false;send(a[0],String.join(" ",Arrays.copyOfRange(a,1,a.length)),plugin.getConfig().getInt("announcements.bossbar-seconds",10));return true;}
 public List<String> onTabComplete(CommandSender s,Command c,String l,String[] a){return a.length==1?List.of("chat","actionbar","title","subtitle","bossbar","stop","pause","resume","list"):List.of();}
}