package dev.mando;
import org.bukkit.Bukkit;import java.io.*;import java.nio.file.*;import java.time.*;import java.time.format.*;import java.util.*;import java.util.zip.*;
public final class BackupManager{
 private final MandoPlugin plugin;private volatile String last="ninguno";
 public BackupManager(MandoPlugin p){plugin=p;}
 public String lastBackup(){return last;}public String createManual(){return create("manual");}public String createCritical(){return create("critical");}public String createShutdown(){return create("shutdown");}
 public void startSchedule(){long minutes=Math.max(30,plugin.getConfig().getLong("backups.scheduled.interval-minutes",360));Bukkit.getScheduler().runTaskTimerAsynchronously(plugin,()->{create("scheduled");rotate("scheduled",plugin.getConfig().getInt("backups.rotation.scheduled",7));},minutes*1200L,minutes*1200L);}
 public synchronized String create(String type){try{Path root=plugin.getDataFolder().toPath();Path dir=root.resolve("backups").resolve(type);Files.createDirectories(dir);String name="mando-"+type+"-"+LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyyMMdd-HHmmss"))+".zip";Path out=dir.resolve(name);try(ZipOutputStream z=new ZipOutputStream(Files.newOutputStream(out))){if(Files.exists(root))try(var walk=Files.walk(root)){walk.filter(Files::isRegularFile).filter(p->!p.startsWith(root.resolve("backups"))).sorted().forEach(p->{try{z.putNextEntry(new ZipEntry(root.relativize(p).toString().replace('\\','/')));Files.copy(p,z);z.closeEntry();}catch(IOException ex){throw new UncheckedIOException(ex);}});}ZipEntry info=new ZipEntry("backup-info.yml");z.putNextEntry(info);z.write(("version: "+plugin.getPluginMeta().getVersion()+"\ntype: "+type+"\ncreated: "+Instant.now()+"\n").getBytes());z.closeEntry();}if(Files.size(out)<=0)throw new IOException("ZIP vacío");try(ZipFile check=new ZipFile(out.toFile())){if(check.getEntry("backup-info.yml")==null||check.getEntry("config.yml")==null)throw new IOException("ZIP incompleto");for(String required:new String[]{"warps.yml","spawn.yml","markers.yml"})if(Files.exists(root.resolve(required))&&check.getEntry(required)==null)throw new IOException("ZIP incompleto: "+required);}last=type+"/"+name;if(type.equals("shutdown"))rotate("shutdown",plugin.getConfig().getInt("backups.rotation.shutdown",3));return name;}catch(Exception ex){plugin.getLogger().severe("Backup "+type+" falló: "+ex.getMessage());return null;}}
 private void rotate(String type,int keep){if(keep<1)return;try{Path dir=plugin.getDataFolder().toPath().resolve("backups").resolve(type);if(!Files.exists(dir))return;List<Path> z;try(var s=Files.list(dir)){z=s.filter(p->p.toString().endsWith(".zip")).sorted(Comparator.comparingLong(this::mtime).reversed()).toList();}for(int i=keep;i<z.size();i++)Files.deleteIfExists(z.get(i));}catch(Exception e){plugin.getLogger().warning("Rotación backup: "+e.getMessage());}}
 private long mtime(Path p){try{return Files.getLastModifiedTime(p).toMillis();}catch(Exception e){return 0;}}
}