package dev.mando;
import org.bukkit.*;import org.bukkit.configuration.file.YamlConfiguration;import org.bukkit.event.*;import org.bukkit.event.entity.PlayerDeathEvent;import org.bukkit.event.player.PlayerTeleportEvent;import java.io.*;import java.util.*;
public final class BackListener implements Listener{
 private final MandoPlugin plugin;private final File file;private final YamlConfiguration y;private final Map<UUID,Location> backs=new HashMap<>();private final Map<UUID,Long> used=new HashMap<>();
 public BackListener(MandoPlugin p){plugin=p;file=new File(p.getDataFolder(),"back.yml");y=YamlConfiguration.loadConfiguration(file);if(p.getConfig().getBoolean("back.persistent",true))load();}
 public Location get(UUID id){Location l=backs.get(id);return l==null?null:l.clone();}
 public long cooldown(org.bukkit.entity.Player p){if(p.hasPermission("mando.back.bypass"))return 0;long wait=Math.max(0,plugin.getConfig().getLong("back.cooldown-seconds",10))*1000L,remain=wait-(System.currentTimeMillis()-used.getOrDefault(p.getUniqueId(),0L));return Math.max(0,(remain+999)/1000);}
 public void markUsed(UUID id){used.put(id,System.currentTimeMillis());}
 public Location safe(Location l){if(l==null||l.getWorld()==null)return null;World w=l.getWorld();if(l.getY()<=w.getMinHeight()+1||!w.getWorldBorder().isInside(l))return null;if(!l.getBlock().getType().isSolid()&&!l.clone().add(0,1,0).getBlock().getType().isSolid())return l;for(int dy=-3;dy<=3;dy++){Location n=l.clone().add(0,dy,0);if(n.getY()<=w.getMinHeight()+1||n.getY()>=w.getMaxHeight()-2)continue;if(!n.getBlock().getType().isSolid()&&!n.clone().add(0,1,0).getBlock().getType().isSolid()&&n.clone().add(0,-1,0).getBlock().getType().isSolid())return n;}return null;}
 public void set(UUID id,Location l){backs.put(id,l.clone());if(plugin.getConfig().getBoolean("back.persistent",true))save(id,l);}
 @EventHandler(priority=EventPriority.MONITOR,ignoreCancelled=true) public void onTeleport(PlayerTeleportEvent e){Location from=e.getFrom(),to=e.getTo();if(to==null)return;if(from.getWorld().equals(to.getWorld())&&from.distanceSquared(to)<1)return;set(e.getPlayer().getUniqueId(),from);}
 @EventHandler(priority=EventPriority.MONITOR) public void onDeath(PlayerDeathEvent e){set(e.getPlayer().getUniqueId(),e.getPlayer().getLocation());}
 private void load(){for(String s:y.getKeys(false))try{UUID id=UUID.fromString(s);World w=Bukkit.getWorld(y.getString(s+".world",""));if(w!=null)backs.put(id,new Location(w,y.getDouble(s+".x"),y.getDouble(s+".y"),y.getDouble(s+".z"),(float)y.getDouble(s+".yaw"),(float)y.getDouble(s+".pitch")));}catch(Exception ignored){}}
 private synchronized void save(UUID id,Location l){String b=id+".";y.set(b+"world",l.getWorld().getName());y.set(b+"x",l.getX());y.set(b+"y",l.getY());y.set(b+"z",l.getZ());y.set(b+"yaw",l.getYaw());y.set(b+"pitch",l.getPitch());try{file.getParentFile().mkdirs();y.save(file);}catch(IOException e){plugin.getLogger().warning("Back save: "+e.getMessage());}}
}