package dev.mando;
import dev.mando.HomeManager.Home;import net.kyori.adventure.text.minimessage.tag.resolver.Placeholder;import org.bukkit.attribute.*;import org.bukkit.command.*;import org.bukkit.entity.Player;import io.papermc.paper.dialog.Dialog;import io.papermc.paper.registry.data.dialog.*;import io.papermc.paper.registry.data.dialog.action.DialogAction;import io.papermc.paper.registry.data.dialog.body.DialogBody;import io.papermc.paper.registry.data.dialog.type.DialogType;import net.kyori.adventure.text.Component;import net.kyori.adventure.text.event.ClickCallback;import java.util.*;
public final class Commands implements CommandExecutor,TabCompleter{
 private static final int MENU_CAP=54;private final MandoPlugin plugin;private final HomeManager homes;private final GodListener god;private final Rtp rtp;private final LocationMarkerManager markers;
 public Commands(MandoPlugin p,HomeManager h,GodListener g,Rtp r,LocationMarkerManager m){plugin=p;homes=h;god=g;rtp=r;markers=m;}
 public boolean onCommand(CommandSender s,Command c,String l,String[] a){if(!(s instanceof Player p)){s.sendMessage(plugin.msg("only-players"));return true;}switch(c.getName().toLowerCase(Locale.ROOT)){case"god"->p.sendMessage(plugin.msg(god.toggle(p)?"god-on":"god-off"));case"heal"->heal(p);case"sethome"->setHome(p,a);case"home"->home(p,a);case"homes"->HomesMenu.open(plugin,homes,p);case"delhome"->delHome(p,a);case"renamehome"->renameHome(p,a);case"restorehome"->restoreHome(p,a);case"rtp"->rtp.start(p);}return true;}
 private void heal(Player p){GodListener.fill(p);if(plugin.getConfig().getBoolean("heal.restore-health",false)){AttributeInstance max=p.getAttribute(Attribute.MAX_HEALTH);if(max!=null)p.setHealth(max.getValue());}p.sendMessage(plugin.msg("heal-done"));}
 private int cap(Player p){if(p.hasPermission("mando.homes.unlimited"))return MENU_CAP;int best=0;for(int n:new int[]{1,3,5,10})if(p.hasPermission("mando.homes."+n))best=n;return Math.min(MENU_CAP,best>0?best:plugin.getConfig().getInt("homes.max",3));}
 private void setHome(Player p,String[] a){String name=a.length==0?plugin.getConfig().getString("homes.default-name","home"):HomeManager.normalize(a[0]);if(name==null){p.sendMessage(plugin.msg("invalid-name"));return;}Map<String,Home> all=homes.all(p.getUniqueId());if(!all.containsKey(name)&&all.size()>=cap(p)){p.sendMessage(plugin.msg("homes-limit",Placeholder.unparsed("max",String.valueOf(cap(p)))));return;}Home next=Home.of(p.getLocation());if(all.containsKey(name)){Home prev=all.get(name);ActionButton yes=button("Actualizar ubicación",pl->applyHome(pl,name,next));ActionButton no=ActionButton.builder(Component.text("Cancelar")).build();p.showDialog(Dialog.create(b->b.empty().base(DialogBase.builder(Component.text("Home existente")).body(List.of(DialogBody.plainMessage(Component.text("Actual: "+coords(prev)+"\nNueva: "+coords(next)+"\n\n¿Actualizar?")))).build()).type(DialogType.confirmation(yes,no))));return;}applyHome(p,name,next);}
 private void applyHome(Player p,String name,Home h){homes.set(p.getUniqueId(),name,h);boolean ok=markers.createHomeSign(p,name);p.sendMessage(plugin.msg("home-set",Placeholder.unparsed("name",name)));if(!ok)p.sendMessage(plugin.msg("home-marker-failed"));}
 private void home(Player p,String[] a){Map<String,Home> all=homes.all(p.getUniqueId());if(all.isEmpty()){p.sendMessage(plugin.msg("no-homes"));return;}String name;if(a.length==0){String def=plugin.getConfig().getString("homes.default-name","home");if(all.containsKey(def))name=def;else if(all.size()==1)name=all.keySet().iterator().next();else{p.sendMessage(plugin.msg("home-choose"));return;}}else name=HomeManager.normalize(a[0]);Home h=name==null?null:all.get(name);if(h==null){p.sendMessage(plugin.msg("home-not-found",Placeholder.unparsed("name",a.length>0?a[0]:"")));return;}homes.teleport(p,name,h);}
 private void delHome(Player p,String[] a){if(a.length==0){p.sendMessage(plugin.msg("home-choose"));return;}String name=HomeManager.normalize(a[0]);if(name==null||!homes.all(p.getUniqueId()).containsKey(name)){p.sendMessage(plugin.msg("home-not-found",Placeholder.unparsed("name",a[0])));return;}ActionButton yes=button("Eliminar",pl->{if(homes.remove(pl.getUniqueId(),name))pl.sendMessage(plugin.msg("home-deleted",Placeholder.unparsed("name",name)));});ActionButton no=ActionButton.builder(Component.text("Cancelar")).build();p.showDialog(Dialog.create(b->b.empty().base(DialogBase.builder(Component.text("Eliminar Home")).body(List.of(DialogBody.plainMessage(Component.text("¿Eliminar definitivamente el Home \""+name+"\"?\nPodrá recuperarse desde el historial administrativo.")))).build()).type(DialogType.confirmation(yes,no))));}
 private void renameHome(Player p,String[] a){if(a.length<2){p.sendMessage("§c/renamehome <actual> <nuevo>");return;}String old=HomeManager.normalize(a[0]),next=HomeManager.normalize(a[1]);if(old==null||next==null){p.sendMessage(plugin.msg("invalid-name"));return;}if(homes.rename(p.getUniqueId(),old,next)){p.sendMessage("§aHome renombrado: §e"+old+" §7→ §e"+next);}else p.sendMessage("§cNo se pudo renombrar: revisa nombres existentes.");}
 private void restoreHome(Player p,String[] a){if(!p.hasPermission("mando.homes.restore")){p.sendMessage(plugin.msg("no-permission"));return;}if(a.length==0){List<String> d=homes.deleted(p.getUniqueId());p.sendMessage(d.isEmpty()?"§7No hay Homes eliminados.":"§eEliminados: §f"+String.join(", ",d));return;}String key=a[0],name=a.length>1?HomeManager.normalize(a[1]):HomeManager.normalize(homes.deletedName(p.getUniqueId(),key));if(name!=null&&homes.restoreDeleted(p.getUniqueId(),key,name))p.sendMessage("§aHome restaurado como §e"+name);else p.sendMessage("§cNo se pudo restaurar ese Home.");}
 private ActionButton button(String text,java.util.function.Consumer<Player> f){return ActionButton.builder(Component.text(text)).action(DialogAction.customClick((r,a)->{if(a instanceof Player p)f.accept(p);},ClickCallback.Options.builder().uses(1).build())).build();}
 private static String coords(Home h){return String.format(Locale.ROOT,"%.1f / %.1f / %.1f",h.x(),h.y(),h.z());}
 public List<String> onTabComplete(CommandSender s,Command c,String l,String[] a){if(!(s instanceof Player p)||a.length!=1)return List.of();String n=c.getName().toLowerCase(Locale.ROOT);if(!List.of("home","sethome","delhome","renamehome").contains(n))return List.of();String q=a[0].toLowerCase(Locale.ROOT);return homes.all(p.getUniqueId()).keySet().stream().filter(x->x.startsWith(q)).toList();}
}