package dev.mando;

import net.kyori.adventure.text.minimessage.tag.resolver.Placeholder;
import org.bukkit.*;import org.bukkit.configuration.*;import org.bukkit.configuration.file.YamlConfiguration;import org.bukkit.entity.Player;
import java.io.*;import java.nio.charset.StandardCharsets;import java.nio.file.*;import java.util.*;import java.util.regex.Pattern;

public final class HomeManager {
 public record Home(String world,double x,double y,double z,float yaw,float pitch){Location toLocation(){World w=Bukkit.getWorld(world);return w==null?null:new Location(w,x,y,z,yaw,pitch);}static Home of(Location l){return new Home(l.getWorld().getName(),l.getX(),l.getY(),l.getZ(),l.getYaw(),0.0f);}}
 private static final Pattern VALID=Pattern.compile("[a-z0-9_-]{1,16}");
 private final MandoPlugin plugin;private final File file,historyFile;private final Object ioLock=new Object();private final YamlConfiguration history;private final Map<UUID,Map<String,Home>> homes=new HashMap<>();
 public HomeManager(MandoPlugin p){plugin=p;file=new File(p.getDataFolder(),"homes.yml");historyFile=new File(p.getDataFolder(),"home-history.yml");history=YamlConfiguration.loadConfiguration(historyFile);load();}
 public static String normalize(String raw){if(raw==null)return null;String n=raw.toLowerCase(Locale.ROOT);return VALID.matcher(n).matches()?n:null;}
 public Map<String,Home> all(UUID id){Map<String,Home> m=homes.get(id);return m==null?Map.of():Collections.unmodifiableMap(m);}
 public void set(UUID id,String name,Home h){Map<String,Home> m=homes.computeIfAbsent(id,k->new TreeMap<>());Home old=m.put(name,h);if(old!=null)writeHome(history,id+".previous."+name,old);saveHistory();saveAsync();}
 public boolean rename(UUID id,String old,String next){Map<String,Home> m=homes.get(id);if(m==null||!m.containsKey(old)||m.containsKey(next))return false;Home h=m.remove(old);m.put(next,h);Home prev=readHome(history,id+".previous."+old);history.set(id+".previous."+old,null);if(prev!=null)writeHome(history,id+".previous."+next,prev);saveHistory();saveAsync();return true;}
 public Home previous(UUID id,String name){return readHome(history,id+".previous."+name);}
 public boolean remove(UUID id,String name){Map<String,Home> m=homes.get(id);if(m==null)return false;Home h=m.remove(name);if(h==null)return false;archive(id,name,h);if(m.isEmpty())homes.remove(id);saveAsync();return true;}
 public void teleport(Player p,String name,Home h){Location l=h.toLocation();if(l==null){p.sendMessage(plugin.msg("home-world-missing"));return;}plugin.teleports().teleport(p,l,"mando.teleport.bypass-warmup",()->p.sendMessage(plugin.msg("home-teleported",Placeholder.unparsed("name",name))));}
 public List<String> deleted(UUID id){return new ArrayList<>(history.getStringList(id+".deleted-order"));}
 public Home deletedHome(UUID id,String key){return readHome(history,id+".deleted."+key+".location");}
 public String deletedName(UUID id,String key){return history.getString(id+".deleted."+key+".name","home");}
 public boolean restoreDeleted(UUID id,String key,String asName){Home h=deletedHome(id,key);if(h==null||homes.getOrDefault(id,Map.of()).containsKey(asName))return false;homes.computeIfAbsent(id,k->new TreeMap<>()).put(asName,h);history.set(id+".deleted."+key,null);List<String> order=new ArrayList<>(history.getStringList(id+".deleted-order"));order.remove(key);history.set(id+".deleted-order",order);saveHistory();saveAsync();return true;}
 private void archive(UUID id,String name,Home h){String key=System.currentTimeMillis()+"-"+name;writeHome(history,id+".deleted."+key+".location",h);history.set(id+".deleted."+key+".name",name);history.set(id+".deleted."+key+".deleted-at",java.time.Instant.now().toString());List<String> order=new ArrayList<>(history.getStringList(id+".deleted-order"));order.add(0,key);int max=Math.max(1,plugin.getConfig().getInt("homes.deleted-history",5));while(order.size()>max){String old=order.remove(order.size()-1);history.set(id+".deleted."+old,null);}history.set(id+".deleted-order",order);saveHistory();}
 private void writeHome(YamlConfiguration y,String b,Home h){y.set(b+".world",h.world());y.set(b+".x",h.x());y.set(b+".y",h.y());y.set(b+".z",h.z());y.set(b+".yaw",h.yaw());y.set(b+".pitch",h.pitch());}
 private Home readHome(YamlConfiguration y,String b){String w=y.getString(b+".world");if(w==null)return null;return new Home(w,y.getDouble(b+".x"),y.getDouble(b+".y"),y.getDouble(b+".z"),(float)y.getDouble(b+".yaw"),(float)y.getDouble(b+".pitch"));}
 private synchronized void saveHistory(){try{historyFile.getParentFile().mkdirs();history.save(historyFile);}catch(IOException e){plugin.getLogger().warning("Home history: "+e.getMessage());}}
 private void load(){if(!file.exists())return;YamlConfiguration y=YamlConfiguration.loadConfiguration(file);for(String u:y.getKeys(false)){UUID id;try{id=UUID.fromString(u);}catch(Exception e){continue;}ConfigurationSection sec=y.getConfigurationSection(u);if(sec==null)continue;Map<String,Home> map=new TreeMap<>();for(String name:sec.getKeys(false)){ConfigurationSection h=sec.getConfigurationSection(name);if(h==null||h.getString("world")==null)continue;map.put(name,new Home(h.getString("world"),h.getDouble("x"),h.getDouble("y"),h.getDouble("z"),(float)h.getDouble("yaw"),(float)h.getDouble("pitch")));}if(!map.isEmpty())homes.put(id,map);}}
 private String serialize(){YamlConfiguration y=new YamlConfiguration();for(var owner:homes.entrySet())for(var e:owner.getValue().entrySet()){String b=owner.getKey()+"."+e.getKey()+".";Home h=e.getValue();y.set(b+"world",h.world());y.set(b+"x",h.x());y.set(b+"y",h.y());y.set(b+"z",h.z());y.set(b+"yaw",h.yaw());y.set(b+"pitch",h.pitch());}return y.saveToString();}
 private void saveAsync(){String d=serialize();Bukkit.getScheduler().runTaskAsynchronously(plugin,()->write(d));}public void saveNow(){write(serialize());}
 private void write(String data){synchronized(ioLock){try{Files.createDirectories(file.getParentFile().toPath());Path tmp=new File(file.getParentFile(),"homes.yml.tmp").toPath();Files.writeString(tmp,data,StandardCharsets.UTF_8);Files.move(tmp,file.toPath(),StandardCopyOption.REPLACE_EXISTING);}catch(IOException e){plugin.getLogger().severe("No se pudo guardar homes.yml: "+e.getMessage());}}}
}