package dev.mando;
import io.papermc.paper.dialog.Dialog;
import io.papermc.paper.registry.data.dialog.*;
import io.papermc.paper.registry.data.dialog.action.DialogAction;
import io.papermc.paper.registry.data.dialog.body.DialogBody;
import io.papermc.paper.registry.data.dialog.type.DialogType;
import io.papermc.paper.registry.data.dialog.input.DialogInput;
import net.kyori.adventure.text.Component;
import net.kyori.adventure.text.event.ClickCallback;
import org.bukkit.Bukkit;import org.bukkit.command.*;import org.bukkit.entity.Player;import java.util.*;
public final class MandoCommand implements CommandExecutor,TabCompleter{
 private final MandoPlugin plugin;public MandoCommand(MandoPlugin p){plugin=p;}
 public boolean onCommand(CommandSender s,Command c,String l,String[] a){
  if(!(s instanceof Player p)){s.sendMessage("Mando: usa los comandos administrativos dentro del juego.");return true;}
  if(a.length>0){
   if(a[0].equalsIgnoreCase("config")){p.performCommand("serverconfig");return true;}
   if(a[0].equalsIgnoreCase("changelog")){p.performCommand("changelog");return true;}
   if(a[0].equalsIgnoreCase("setup")){showSetup(p,false);return true;}
   if(a[0].equalsIgnoreCase("status")){showStatus(p);return true;}
   if(a[0].equalsIgnoreCase("providers")){showProviders(p);return true;}
   if(a[0].equalsIgnoreCase("provider")&&a.length>=3){String cap=a[1].toLowerCase(Locale.ROOT);if(plugin.integrations().selectProvider(cap,a[2]))p.sendMessage("§6Mando §8» §aProveedor "+cap+": §f"+a[2]);else p.sendMessage("§cProveedor o capacidad no disponible.");return true;}
   if(a[0].equalsIgnoreCase("reload")){if(!p.isOp()){p.sendMessage(plugin.msg("no-permission"));return true;}plugin.reloadConfig();plugin.integrations().refresh();p.sendMessage("§6Mando §8» §aConfiguración recargada. Los cambios que requieren reinicio siguen pendientes.");return true;}
   if(a[0].equalsIgnoreCase("stop")){if(!p.isOp()){p.sendMessage(plugin.msg("no-permission"));return true;}if(a.length>1&&a[1].equalsIgnoreCase("cancel")){plugin.shutdown().cancel(true);return true;}if(a.length<2){p.sendMessage("§c/mando stop <minutos|cancel>");return true;}try{int min=Integer.parseInt(a[1]);if(!plugin.shutdown().scheduleMinutes(min))p.sendMessage("§cMinutos inválidos.");}catch(NumberFormatException ex){p.sendMessage("§c/mando stop <minutos|cancel>");}return true;}
   if(a[0].equalsIgnoreCase("cleanup")&&a.length>1&&a[1].equalsIgnoreCase("markers")){if(!p.isOp()){p.sendMessage(plugin.msg("no-permission"));return true;}int n=plugin.markers().cleanupRegistered();p.sendMessage("§aRegistro de marcadores limpiado: "+n+" entradas inválidas.");return true;}
   if(a[0].equalsIgnoreCase("diagnose")){if(!p.isOp()){p.sendMessage(plugin.msg("no-permission"));return true;}String d=plugin.diagnostics().create();p.sendMessage(d==null?"§cNo se pudo crear diagnóstico.":"§aDiagnóstico creado: "+d);return true;}
   if(a[0].equalsIgnoreCase("reset")){if(!p.isOp()){p.sendMessage(plugin.msg("no-permission"));return true;}ActionButton yes=button("Restablecer setup","Marca el asistente como pendiente",pl->{plugin.getConfig().set("setup.completed",false);plugin.saveConfig();pl.sendMessage("§6Mando §8» §eEl asistente volverá a mostrarse en la próxima sesión.");});ActionButton no=ActionButton.builder(Component.text("Cancelar")).build();p.showDialog(Dialog.create(b->b.empty().base(DialogBase.builder(Component.text("Restablecer Mando")).body(List.of(DialogBody.plainMessage(Component.text("Esto no borra Homes, correo ni datos. Solo vuelve a dejar pendiente el asistente de configuración.")))).build()).type(DialogType.confirmation(yes,no))));return true;}
   if(a[0].equalsIgnoreCase("backup")){if(!p.isOp()){p.sendMessage(plugin.msg("no-permission"));return true;}String name=plugin.backups().createManual();p.sendMessage(Component.text(name==null?"No se pudo crear el backup.":"Backup creado: "+name));return true;}
  }showMain(p);return true;
 }
 private void showStatus(Player p){String body="Mando "+plugin.getPluginMeta().getVersion()+"\\nPlataforma: "+plugin.platform().platform()+"\\nMinecraft: "+Bukkit.getMinecraftVersion()+"\\nStorage: YAML\\nSetup: "+(plugin.getConfig().getBoolean("setup.completed",false)?"completado":"pendiente")+"\\nHomes: "+state("homes")+" · Warps: "+state("warps")+" · Spawn: "+state("spawn")+"\\nÚltimo backup: "+plugin.backups().lastBackup()+"\\nReinicio programado: "+(plugin.shutdown().active()?plugin.shutdown().secondsLeft()+"s":"no")+"\\n\\nIntegraciones / proveedores:\\n"+plugin.integrations().summary();p.showDialog(Dialog.create(x->x.empty().base(DialogBase.builder(Component.text("Mando · Estado")).body(List.of(DialogBody.plainMessage(Component.text(body)))).build()).type(DialogType.notice())));}
 private String state(String m){return plugin.getConfig().getBoolean("modules."+m+".enabled",true)?"activo":"desactivado";}
 public void showMain(Player p){ActionButton config=button("Configurar servidor","Abrir ServerConfig",pl->pl.performCommand("serverconfig"));ActionButton status=button("Estado","Ver estado de Mando",pl->pl.performCommand("mando status"));String body="Servidor: "+Bukkit.getName()+" "+Bukkit.getMinecraftVersion()+"\\n\\nMando centraliza configuración, ubicaciones, comunicación e integraciones.\\n\\nBuild de prueba "+plugin.getPluginMeta().getVersion()+".";p.showDialog(Dialog.create(x->x.empty().base(DialogBase.builder(Component.text("Mando · Administración")).body(List.of(DialogBody.plainMessage(Component.text(body)))).build()).type(DialogType.confirmation(config,status))));}
 private void showProviders(Player p){StringBuilder body=new StringBuilder("Selecciona proveedores explícitamente con /mando provider <capacidad> <proveedor>\n\n");for(var e:plugin.integrations().providers().entrySet())body.append(e.getKey()).append(": ").append(e.getValue().selected()).append(" · disponibles: ").append(String.join(", ",plugin.integrations().candidates(e.getKey()))).append("\n");p.showDialog(Dialog.create(x->x.empty().base(DialogBase.builder(Component.text("Mando · Proveedores")).body(List.of(DialogBody.plainMessage(Component.text(body.toString())))).build()).type(DialogType.notice())));}
 public void showSetup(Player p,boolean first){plugin.setupProtection().begin(p);setupBasics(p,first);}
 private void setupBasics(Player p,boolean first){ActionButton next=ActionButton.builder(Component.text("Siguiente")).action(DialogAction.customClick((r,a)->{if(!(a instanceof Player pl))return;String lang=Objects.requireNonNullElse(r.getText("language"),"es").trim().toLowerCase(Locale.ROOT);plugin.getConfig().set("language",lang.isBlank()?"es":lang);Boolean markers=r.getBoolean("markers");if(markers!=null)plugin.getConfig().set("markers.homes.enabled",markers);String homes=Objects.requireNonNullElse(r.getText("homes"),"3");try{plugin.getConfig().set("homes.max",Math.max(1,Integer.parseInt(homes)));}catch(Exception ignored){}plugin.saveConfig();setupTeleport(pl);},ClickCallback.Options.builder().uses(1).build())).build();ActionButton later=button("Más tarde","Cerrar sin completar",pl->plugin.setupProtection().end(pl));p.showDialog(Dialog.create(b->b.empty().base(DialogBase.builder(Component.text(first?"Bienvenido a Mando":"Mando · Configuración 1/4")).body(List.of(DialogBody.plainMessage(Component.text("Idioma, Homes y marcadores. Puedes volver a ejecutar /mando setup.")))).inputs(List.of(DialogInput.text("language",Component.text("Idioma")).initial(plugin.getConfig().getString("language","es")).maxLength(12).width(180).build(),DialogInput.text("homes",Component.text("Homes por defecto")).initial(String.valueOf(plugin.getConfig().getInt("homes.max",3))).maxLength(3).width(120).build(),DialogInput.bool("markers",Component.text("Marcadores de Homes")).initial(plugin.getConfig().getBoolean("markers.homes.enabled",true)).build())).build()).type(DialogType.confirmation(next,later))));}
 private void setupTeleport(Player p){ActionButton next=ActionButton.builder(Component.text("Siguiente")).action(DialogAction.customClick((r,a)->{if(!(a instanceof Player pl))return;try{plugin.getConfig().set("teleport.warmup",Math.max(0,Integer.parseInt(Objects.requireNonNullElse(r.getText("warmup"),"3"))));plugin.getConfig().set("teleport.cooldown",Math.max(0,Integer.parseInt(Objects.requireNonNullElse(r.getText("cooldown"),"5"))));}catch(Exception ignored){}Boolean rtp=r.getBoolean("rtp"),persist=r.getBoolean("back_persistent"),adminBack=r.getBoolean("admin_back");if(rtp!=null)plugin.getConfig().set("modules.rtp.enabled",rtp);if(persist!=null)plugin.getConfig().set("back.persistent",persist);if(adminBack!=null)plugin.getConfig().set("back.admin-teleport-creates-back",adminBack);plugin.saveConfig();setupServices(pl);},ClickCallback.Options.builder().uses(1).build())).build();p.showDialog(Dialog.create(b->b.empty().base(DialogBase.builder(Component.text("Mando · Configuración 2/4")).body(List.of(DialogBody.plainMessage(Component.text("Teletransportes y RTP.")))).inputs(List.of(DialogInput.text("warmup",Component.text("Warmup (segundos)")).initial(String.valueOf(plugin.getConfig().getInt("teleport.warmup",3))).maxLength(3).width(120).build(),DialogInput.text("cooldown",Component.text("Cooldown (segundos)")).initial(String.valueOf(plugin.getConfig().getInt("teleport.cooldown",5))).maxLength(3).width(120).build(),DialogInput.bool("rtp",Component.text("RTP de Mando")).initial(plugin.getConfig().getBoolean("modules.rtp.enabled",true)).build(),DialogInput.bool("back_persistent",Component.text("Back persistente")).initial(plugin.getConfig().getBoolean("back.persistent",true)).build(),DialogInput.bool("admin_back",Component.text("TP admin crea Back")).initial(plugin.getConfig().getBoolean("back.admin-teleport-creates-back",true)).build())).build()).type(DialogType.confirmation(next,ActionButton.builder(Component.text("Cancelar")).build()))));}
 private void setupServices(Player p){ActionButton next=ActionButton.builder(Component.text("Proveedores")).action(DialogAction.customClick((r,a)->{if(!(a instanceof Player pl))return;Boolean mail=r.getBoolean("mail"),ann=r.getBoolean("announcements"),mounts=r.getBoolean("mounts"),mobs=r.getBoolean("mobs"),gameplay=r.getBoolean("gameplay"),breeding=r.getBoolean("breeding"),raids=r.getBoolean("raids");if(mail!=null)plugin.getConfig().set("mail.enabled",mail);if(ann!=null)plugin.getConfig().set("announcements.enabled",ann);if(mounts!=null)plugin.getConfig().set("modules.server-config.purpur.mounts.enabled",mounts);if(mobs!=null)plugin.getConfig().set("modules.server-config.purpur.mobs.enabled",mobs);if(gameplay!=null)plugin.getConfig().set("modules.server-config.purpur.gameplay.enabled",gameplay);if(breeding!=null)plugin.getConfig().set("modules.server-config.purpur.breeding.enabled",breeding);if(raids!=null)plugin.getConfig().set("modules.server-config.purpur.raids.enabled",raids);plugin.saveConfig();setupProviders(pl);},ClickCallback.Options.builder().uses(1).build())).build();String providers=plugin.integrations().summary();p.showDialog(Dialog.create(b->b.empty().base(DialogBase.builder(Component.text("Mando · Configuración 3/4")).body(List.of(DialogBody.plainMessage(Component.text("Servicios e integraciones detectadas:\n"+providers)))).inputs(List.of(DialogInput.bool("mail",Component.text("Mail")).initial(plugin.getConfig().getBoolean("mail.enabled",true)).build(),DialogInput.bool("announcements",Component.text("Anuncios automáticos")).initial(plugin.getConfig().getBoolean("announcements.enabled",false)).build(),DialogInput.bool("mounts",Component.text("Purpur Mounts")).initial(plugin.getConfig().getBoolean("modules.server-config.purpur.mounts.enabled",false)).build(),DialogInput.bool("mobs",Component.text("Purpur Mob Manager")).initial(plugin.getConfig().getBoolean("modules.server-config.purpur.mobs.enabled",true)).build(),DialogInput.bool("gameplay",Component.text("Purpur Gameplay")).initial(plugin.getConfig().getBoolean("modules.server-config.purpur.gameplay.enabled",true)).build(),DialogInput.bool("breeding",Component.text("Purpur Breeding")).initial(plugin.getConfig().getBoolean("modules.server-config.purpur.breeding.enabled",true)).build(),DialogInput.bool("raids",Component.text("Purpur Raids")).initial(plugin.getConfig().getBoolean("modules.server-config.purpur.raids.enabled",true)).build())).build()).type(DialogType.confirmation(next,ActionButton.builder(Component.text("Cancelar")).build()))));}
 private void setupProviders(Player p){ActionButton finish=ActionButton.builder(Component.text("Finalizar")).action(DialogAction.customClick((r,a)->{if(!(a instanceof Player pl))return;for(String cap:List.of("homes","warps","global-spawn","first-join-spawn","respawn","spawn-command","back","rtp","afk")){String selected=Objects.requireNonNullElse(r.getText("p_"+cap),plugin.getConfig().getString("providers."+cap,cap.contains("spawn")?plugin.getConfig().getString("providers.spawn","Mando"):"Mando")).trim();if(!plugin.integrations().selectProvider(cap,selected)){pl.sendMessage("§eProveedor no disponible para "+cap+": "+selected+". Se conserva el actual.");}}plugin.getConfig().set("setup.completed",true);plugin.saveConfig();plugin.integrations().refresh();plugin.setupProtection().end(pl);pl.sendMessage("§6Mando §8» §aConfiguración inicial completada.");},ClickCallback.Options.builder().uses(1).build())).build();List<DialogInput> inputs=new ArrayList<>();for(String cap:List.of("homes","warps","spawn","back","rtp","afk"))inputs.add(DialogInput.text("p_"+cap,Component.text("Proveedor "+cap)).initial(plugin.getConfig().getString("providers."+cap,"Mando")).maxLength(24).width(220).build());p.showDialog(Dialog.create(b->b.empty().base(DialogBase.builder(Component.text("Mando · Configuración 4/4")).body(List.of(DialogBody.plainMessage(Component.text("Elige explícitamente quién controla cada capacidad. Disponibles actuales:\n"+plugin.integrations().summary())))).inputs(inputs).build()).type(DialogType.confirmation(finish,ActionButton.builder(Component.text("Cancelar")).build()))));}
 private ActionButton button(String t,String tip,java.util.function.Consumer<Player> action){return ActionButton.builder(Component.text(t)).tooltip(Component.text(tip)).action(DialogAction.customClick((r,a)->{if(a instanceof Player p)action.accept(p);},ClickCallback.Options.builder().uses(1).build())).build();}
 public List<String> onTabComplete(CommandSender s,Command c,String a,String[] x){return x.length==1?List.of("setup","config","status","providers","provider","reload","stop","backup","cleanup","diagnose","reset","changelog"):List.of();}
}