package dev.mando;
import io.papermc.paper.dialog.Dialog;import io.papermc.paper.registry.data.dialog.*;import io.papermc.paper.registry.data.dialog.action.DialogAction;import io.papermc.paper.registry.data.dialog.body.DialogBody;import io.papermc.paper.registry.data.dialog.type.DialogType;import net.kyori.adventure.text.Component;import net.kyori.adventure.text.event.ClickCallback;import org.bukkit.*;import org.bukkit.command.*;import org.bukkit.entity.Player;import java.util.*;
public final class SocialCommands implements CommandExecutor,TabCompleter{
 private final MandoPlugin plugin;private final TpaManager tpa;private final MailManager mail;private final HomeManager homes;private final PlayerDataManager players;private final DeathManager deaths;private final AuditLogger audit;private final EconomyBridge economy=new EconomyBridge();
 public SocialCommands(MandoPlugin p,TpaManager t,MailManager m,HomeManager h,PlayerDataManager pd,DeathManager d,AuditLogger a){plugin=p;tpa=t;mail=m;homes=h;players=pd;deaths=d;audit=a;}
 public boolean onCommand(CommandSender s,Command c,String l,String[] a){if(!(s instanceof Player p))return true;String n=c.getName().toLowerCase(Locale.ROOT);
  if(n.equals("tptoggle")){p.sendMessage("§6Mando §8» "+(tpa.toggle(p)?"§aTPA activado":"§cTPA desactivado"));return true;}
  if(n.equals("tpaccept")){p.sendMessage(tpa.accept(p));return true;}if(n.equals("tpdeny")){p.sendMessage(tpa.deny(p));return true;}if(n.equals("tpcancel")){p.sendMessage(tpa.cancel(p));return true;}
  if(n.equals("tpa")||n.equals("tpahere")){if(a.length<1){p.sendMessage("§c/"+n+" <jugador>");return true;}Player to=Bukkit.getPlayerExact(a[0]);p.sendMessage(to==null?"§cJugador offline.":tpa.request(p,to,n.equals("tpahere")));return true;}
  if(n.equals("mail"))return mailCommand(p,a);
  if(n.equals("profile")){openProfile(p,a.length==0?p.getUniqueId():resolveKnown(a[0]),a.length>0);return true;}return true;}
 private boolean mailCommand(Player p,String[] a){if(a.length==0||a[0].equalsIgnoreCase("inbox")){openInbox(p,p.getUniqueId(),false);return true;}
  if(a[0].equalsIgnoreCase("read")&&a.length>1){int i=parse(a[1])-1;MailManager.Message m=mail.read(p.getUniqueId(),i);if(m==null){p.sendMessage("§cMensaje inexistente.");return true;}showMail(p,m,i+1,false);return true;}
  if(a[0].equalsIgnoreCase("delete")&&a.length>1){p.sendMessage(mail.delete(p.getUniqueId(),parse(a[1])-1)?"§aMensaje eliminado.":"§cMensaje inexistente.");return true;}
  if(a[0].equalsIgnoreCase("inspect")&&a.length>1&&p.hasPermission("mando.mail.inspect")){UUID id=resolveKnown(a[1]);if(id==null){p.sendMessage("§cJugador desconocido.");return true;}audit.log(p.getName(),players.lastName(id),"MAIL_INSPECT","sin marcar como leído");openInbox(p,id,true);return true;}
  if((a[0].equalsIgnoreCase("block")||a[0].equalsIgnoreCase("unblock"))&&a.length>1){UUID id=resolveKnown(a[1]);if(id==null){p.sendMessage("§cJugador desconocido.");return true;}boolean block=a[0].equalsIgnoreCase("block");players.setMailBlocked(p.getUniqueId(),id,block);p.sendMessage(block?"§aJugador bloqueado para correo.":"§aJugador desbloqueado para correo.");return true;}
  if(a.length<2){p.sendMessage("§c/mail <jugador> <mensaje> | /mail inbox | /mail read <n> | /mail delete <n> | /mail block <jugador>");return true;}OfflinePlayer to=Bukkit.getOfflinePlayer(a[0]);if(!to.hasPlayedBefore()&&!to.isOnline()){p.sendMessage("§cJugador desconocido.");return true;}String text=String.join(" ",Arrays.copyOfRange(a,1,a.length));if(text.length()>plugin.getConfig().getInt("mail.max-length",500)){p.sendMessage("§cMensaje demasiado largo.");return true;}p.sendMessage(mail.send(p.getUniqueId(),p.getName(),to.getUniqueId(),to.getName()==null?a[0]:to.getName(),text));return true;}
 private void openInbox(Player viewer,UUID owner,boolean inspect){List<MailManager.Message> ms=mail.messages(owner);StringBuilder b=new StringBuilder();b.append(inspect?"Inspección de correo":"Bandeja de entrada").append("\n\n");if(ms.isEmpty())b.append("No hay mensajes.");else for(int i=0;i<ms.size();i++){MailManager.Message m=ms.get(i);b.append(i+1).append(". ").append(m.read()?"§7":"§e● ").append(m.fromName()).append(" §8· ").append(shortText(m.text())).append("\n");}b.append("\n").append(inspect?"Usa /mail inspect nuevamente tras revisar el archivo de auditoría.":"Usa /mail read <n> para abrir y /mail delete <n> para borrar.");viewer.showDialog(Dialog.create(x->x.empty().base(DialogBase.builder(Component.text("Correo · "+players.lastName(owner))).body(List.of(DialogBody.plainMessage(Component.text(b.toString())))).build()).type(DialogType.notice())));}
 private void showMail(Player p,MailManager.Message m,int n,boolean inspect){String body="De: "+m.fromName()+"\nFecha: "+m.sent()+"\n\n"+m.text()+"\n\n"+(inspect?"Inspección administrativa":"Responder: /mail "+m.fromName()+" <mensaje>");p.showDialog(Dialog.create(x->x.empty().base(DialogBase.builder(Component.text("Mensaje #"+n)).body(List.of(DialogBody.plainMessage(Component.text(body)))).build()).type(DialogType.notice())));}
 private void openProfile(Player viewer,UUID id,boolean other){if(id==null){viewer.sendMessage("§cJugador desconocido.");return;}if(other&&!viewer.hasPermission("mando.profile.others")){viewer.sendMessage("§cSin permiso.");return;}Player target=Bukkit.getPlayer(id);String name=target!=null?target.getName():players.lastName(id);StringBuilder b=new StringBuilder();b.append("§f").append(name).append("\n\n§6Homes §f").append(homes.all(id).size()).append("\n§6Correo §f").append(mail.unread(id)).append(" sin leer / ").append(mail.total(id)).append(" total\n§6Muertes guardadas §f").append(deaths.list(id).size()).append("\n§6TPA §f").append(target!=null?(tpa.disabled(target)?"desactivado":"activo"):(players.tpaEnabled(id)?"activo":"desactivado"));if(target!=null){b.append("\n§6Tiempo jugado §f").append(target.getStatistic(Statistic.PLAY_ONE_MINUTE)/1200).append(" min");b.append("\n§6AFK §f").append(plugin.afk().isAfk(target)?"sí":"no");}
  OfflinePlayer off=Bukkit.getOfflinePlayer(id);String bal=economy.balance(off);if(bal!=null)b.append("\n§6Balance §f").append(bal);
  if(!other)b.append("\n§6Límite Homes §f").append(homeLimit(viewer));
  if(other)b.append("\n\n§8UUID: ").append(id);
  ActionButton left=ActionButton.builder(Component.text(other?"Inspeccionar correo":"Abrir correo")).action(DialogAction.customClick((r,a)->{if(a instanceof Player pl){if(other){if(pl.hasPermission("mando.mail.inspect")){audit.log(pl.getName(),name,"MAIL_INSPECT","desde profile");openInbox(pl,id,true);}}else openInbox(pl,id,false);}},ClickCallback.Options.builder().uses(1).build())).build();
  ActionButton right=ActionButton.builder(Component.text(other?"Cerrar":"Abrir Homes")).action(DialogAction.customClick((r,a)->{if(a instanceof Player pl&&!other)HomesMenu.open(plugin,homes,pl);},ClickCallback.Options.builder().uses(1).build())).build();
  viewer.showDialog(Dialog.create(x->x.empty().base(DialogBase.builder(Component.text("Perfil · "+name)).body(List.of(DialogBody.plainMessage(Component.text(b.toString())))).build()).type(DialogType.confirmation(left,right))));}
 private UUID resolveKnown(String name){Player p=Bukkit.getPlayerExact(name);if(p!=null)return p.getUniqueId();OfflinePlayer o=Bukkit.getOfflinePlayer(name);return o.hasPlayedBefore()?o.getUniqueId():null;}
 private int homeLimit(Player p){if(p.hasPermission("mando.homes.unlimited"))return Integer.MAX_VALUE;int max=plugin.getConfig().getInt("homes.max",3);for(int n:new int[]{1,3,5,10})if(p.hasPermission("mando.homes."+n))max=Math.max(max,n);return max;}
 private int parse(String s){try{return Integer.parseInt(s);}catch(Exception e){return -1;}}private String shortText(String s){return s.length()>45?s.substring(0,45)+"…":s;}
 public List<String> onTabComplete(CommandSender s,Command c,String l,String[] a){if(a.length!=1)return List.of();String q=a[0].toLowerCase(Locale.ROOT);if(c.getName().equalsIgnoreCase("mail"))return List.of("inbox","read","delete","inspect","block","unblock").stream().filter(x->x.startsWith(q)).toList();return Bukkit.getOnlinePlayers().stream().map(Player::getName).filter(x->x.toLowerCase(Locale.ROOT).startsWith(q)).toList();}
}