package dev.mando;
import io.papermc.paper.dialog.Dialog;import io.papermc.paper.registry.data.dialog.*;import io.papermc.paper.registry.data.dialog.action.DialogAction;import io.papermc.paper.registry.data.dialog.body.DialogBody;import io.papermc.paper.registry.data.dialog.type.DialogType;import io.papermc.paper.registry.data.dialog.input.DialogInput;import net.kyori.adventure.text.Component;import net.kyori.adventure.text.event.ClickCallback;import org.bukkit.*;import org.bukkit.command.*;import org.bukkit.entity.Player;import java.util.*;
public final class SocialCommands implements CommandExecutor,TabCompleter{
 private final MandoPlugin plugin;private final TpaManager tpa;private final MailManager mail;private final HomeManager homes;private final PlayerDataManager players;private final DeathManager deaths;private final AuditLogger audit;private final EconomyBridge economy=new EconomyBridge();
 public SocialCommands(MandoPlugin p,TpaManager t,MailManager m,HomeManager h,PlayerDataManager pd,DeathManager d,AuditLogger a){plugin=p;tpa=t;mail=m;homes=h;players=pd;deaths=d;audit=a;}
 public boolean onCommand(CommandSender s,Command c,String l,String[] a){if(!(s instanceof Player p))return true;String n=c.getName().toLowerCase(Locale.ROOT);
  if(n.equals("tptoggle")){p.sendMessage("§6Mando §8» "+(tpa.toggle(p)?"§aTPA activado":"§cTPA desactivado"));return true;}
  if(n.equals("tpaccept")){p.sendMessage(tpa.accept(p));return true;}if(n.equals("tpdeny")){p.sendMessage(tpa.deny(p));return true;}if(n.equals("tpcancel")){p.sendMessage(tpa.cancel(p));return true;}
  if(n.equals("tpa")||n.equals("tpahere")){if(a.length<1){p.sendMessage("§c/"+n+" <jugador>");return true;}Player to=Bukkit.getPlayerExact(a[0]);p.sendMessage(to==null?"§cJugador offline.":tpa.request(p,to,n.equals("tpahere")));return true;}
  if(n.equals("mail")){if(!plugin.getConfig().getBoolean("mail.enabled",true)){p.sendMessage("§cMail está desactivado.");return true;}return mailCommand(p,a);}
  if(n.equals("profile")){
   if(a.length==0){openProfile(p,p.getUniqueId(),false);return true;}
   UUID id=resolveKnown(a[0]);if(id==null){p.sendMessage("§cJugador desconocido.");return true;}
   if(!p.hasPermission("mando.profile.others")){p.sendMessage("§cSin permiso.");return true;}
   if(a.length>=3&&a[1].equalsIgnoreCase("home")){String hn=HomeManager.normalize(a[2]);HomeManager.Home h=hn==null?null:homes.all(id).get(hn);if(h==null||h.toLocation()==null){p.sendMessage("§cHome no disponible.");return true;}p.teleportAsync(h.toLocation());return true;}
   if(a.length>=3&&a[1].equalsIgnoreCase("previous")){String hn=HomeManager.normalize(a[2]);HomeManager.Home h=hn==null?null:homes.previous(id,hn);if(h==null||h.toLocation()==null){p.sendMessage("§cUbicación anterior no disponible.");return true;}p.teleportAsync(h.toLocation());audit.log(p.getName(),players.lastName(id),"HOME_PREVIOUS_VISIT",hn);return true;}
   if(a.length>=3&&a[1].equalsIgnoreCase("deleted")){HomeManager.Home h=homes.deletedHome(id,a[2]);if(h==null||h.toLocation()==null){p.sendMessage("§cHome eliminado no disponible.");return true;}p.teleportAsync(h.toLocation());audit.log(p.getName(),players.lastName(id),"HOME_DELETED_VISIT",a[2]);return true;}
   if(a.length>=3&&a[1].equalsIgnoreCase("death")){int ix=parse(a[2])-1;List<DeathManager.Death> ds=deaths.list(id);if(ix<0||ix>=ds.size()){p.sendMessage("§cMuerte inexistente.");return true;}Location dl=deaths.location(ds.get(ix));if(dl==null){p.sendMessage("§cUbicación no disponible.");return true;}p.teleportAsync(dl);return true;}
   openProfile(p,id,true);return true;}return true;}
 private boolean mailCommand(Player p,String[] a){if(a.length==0||a[0].equalsIgnoreCase("inbox")){openInbox(p,p.getUniqueId(),false);return true;}
  if(a[0].equalsIgnoreCase("read")&&a.length>1){int i=parse(a[1])-1;MailManager.Message m=mail.read(p.getUniqueId(),i);if(m==null){p.sendMessage("§cMensaje inexistente.");return true;}showMail(p,m,i+1,false);return true;}
  if(a[0].equalsIgnoreCase("delete")&&a.length>1){p.sendMessage(mail.delete(p.getUniqueId(),parse(a[1])-1)?"§aMensaje eliminado.":"§cMensaje inexistente.");return true;}
  if(a[0].equalsIgnoreCase("inspect")&&a.length>1&&p.hasPermission("mando.mail.inspect")){UUID id=resolveKnown(a[1]);if(id==null){p.sendMessage("§cJugador desconocido.");return true;}audit.log(p.getName(),players.lastName(id),"MAIL_INSPECT","sin marcar como leído");openInbox(p,id,true);return true;}
  if((a[0].equalsIgnoreCase("block")||a[0].equalsIgnoreCase("unblock"))&&a.length>1){UUID id=resolveKnown(a[1]);if(id==null){p.sendMessage("§cJugador desconocido.");return true;}boolean block=a[0].equalsIgnoreCase("block");players.setMailBlocked(p.getUniqueId(),id,block);p.sendMessage(block?"§aJugador bloqueado para correo.":"§aJugador desbloqueado para correo.");return true;}
  if(a.length==1){UUID id=resolveKnown(a[0]);if(id==null){p.sendMessage("§cJugador desconocido.");return true;}openCompose(p,id,players.lastName(id));return true;}OfflinePlayer to=Bukkit.getOfflinePlayer(a[0]);if(!to.hasPlayedBefore()&&!to.isOnline()){p.sendMessage("§cJugador desconocido.");return true;}String text=String.join(" ",Arrays.copyOfRange(a,1,a.length));if(text.length()>plugin.getConfig().getInt("mail.max-length",500)){p.sendMessage("§cMensaje demasiado largo.");return true;}p.sendMessage(mail.send(p.getUniqueId(),p.getName(),to.getUniqueId(),to.getName()==null?a[0]:to.getName(),text));return true;}
 private void openCompose(Player p,UUID to,String toName){ActionButton send=ActionButton.builder(Component.text("Enviar")).action(DialogAction.customClick((response,audience)->{if(!(audience instanceof Player pl))return;String text=response.getText("message");pl.sendMessage(mail.send(pl.getUniqueId(),pl.getName(),to,toName,text==null?"":text));},ClickCallback.Options.builder().uses(1).build())).build();ActionButton cancel=ActionButton.builder(Component.text("Cancelar")).build();p.showDialog(Dialog.create(b->b.empty().base(DialogBase.builder(Component.text("Correo para "+toName)).body(List.of(DialogBody.plainMessage(Component.text("Escribe el mensaje. Máximo "+plugin.getConfig().getInt("mail.max-length",500)+" caracteres.")))).inputs(List.of(DialogInput.text("message",Component.text("Mensaje")).maxLength(plugin.getConfig().getInt("mail.max-length",500)).width(300).build())).build()).type(DialogType.confirmation(send,cancel))));}
 private void openInbox(Player viewer,UUID owner,boolean inspect){List<MailManager.Message> ms=mail.messages(owner);StringBuilder b=new StringBuilder();b.append(inspect?"Inspección de correo":"Bandeja de entrada").append("\n\n");if(ms.isEmpty())b.append("No hay mensajes.");else for(int i=0;i<ms.size();i++){MailManager.Message m=ms.get(i);b.append(i+1).append(". ").append(m.read()?"§7":"§e● ").append(m.fromName()).append(" §8· ").append(shortText(m.text())).append("\n");}b.append("\n").append(inspect?"Usa /mail inspect nuevamente tras revisar el archivo de auditoría.":"Usa /mail read <n> para abrir y /mail delete <n> para borrar.");viewer.showDialog(Dialog.create(x->x.empty().base(DialogBase.builder(Component.text("Correo · "+players.lastName(owner))).body(List.of(DialogBody.plainMessage(Component.text(b.toString())))).build()).type(DialogType.notice())));}
 private void showMail(Player p,MailManager.Message m,int n,boolean inspect){String body="De: "+m.fromName()+"\nFecha: "+m.sent()+"\n\n"+m.text();if(inspect){p.showDialog(Dialog.create(x->x.empty().base(DialogBase.builder(Component.text("Mensaje #"+n)).body(List.of(DialogBody.plainMessage(Component.text(body)))).build()).type(DialogType.notice())));return;}ActionButton reply=ActionButton.builder(Component.text("Responder")).action(DialogAction.customClick((r,a)->{if(a instanceof Player pl)openCompose(pl,m.from(),m.fromName());},ClickCallback.Options.builder().uses(1).build())).build();ActionButton close=ActionButton.builder(Component.text("Cerrar")).build();p.showDialog(Dialog.create(x->x.empty().base(DialogBase.builder(Component.text("Mensaje #"+n)).body(List.of(DialogBody.plainMessage(Component.text(body)))).build()).type(DialogType.confirmation(reply,close))));}
 private void openProfile(Player viewer,UUID id,boolean other){if(id==null){viewer.sendMessage("§cJugador desconocido.");return;}if(other&&!viewer.hasPermission("mando.profile.others")){viewer.sendMessage("§cSin permiso.");return;}Player target=Bukkit.getPlayer(id);String name=target!=null?target.getName():players.lastName(id);StringBuilder b=new StringBuilder();b.append("§f").append(name).append("\n\n§6Homes §f").append(homes.all(id).size()).append("\n§6Correo §f").append(mail.unread(id)).append(" sin leer / ").append(mail.total(id)).append(" total\n§6Muertes guardadas §f").append(deaths.list(id).size()).append("\n§6TPA §f").append(target!=null?(tpa.disabled(target)?"desactivado":"activo"):(players.tpaEnabled(id)?"activo":"desactivado"));if(target!=null){b.append("\n§6Tiempo jugado §f").append(target.getStatistic(Statistic.PLAY_ONE_MINUTE)/1200).append(" min");b.append("\n§6AFK §f").append(plugin.afk().isAfk(target)?"sí":"no");b.append("\n§6Distancia §f").append(String.format(Locale.ROOT,"%.1f km",distanceKm(target)));}
  OfflinePlayer off=Bukkit.getOfflinePlayer(id);String bal=economy.balance(off);if(bal!=null)b.append("\n§6Balance §f").append(bal);
  if(!other){b.append("\n§6Límite Homes §f").append(homeLimit(viewer));b.append("\n§6Acciones §fCorreo · Homes · TPA");}
  if(other){b.append("\n\n§8UUID: ").append(id);if(!homes.all(id).isEmpty()){b.append("\n\n§6Homes actuales");for(var e:homes.all(id).entrySet()){HomeManager.Home h=e.getValue();b.append("\n§f").append(e.getKey()).append(" §8").append(String.format(Locale.ROOT,"%.1f %.1f %.1f",h.x(),h.y(),h.z()));HomeManager.Home prev=homes.previous(id,e.getKey());if(prev!=null)b.append(" §7(prev: /profile ").append(name).append(" previous ").append(e.getKey()).append(")");}b.append("\n§7Visitar: /profile ").append(name).append(" home <home>");}List<DeathManager.Death> ds=deaths.list(id);if(!ds.isEmpty()){b.append("\n\n§6Últimas muertes");for(int i=0;i<ds.size();i++){DeathManager.Death d=ds.get(i);b.append("\n§f#").append(i+1).append(" §8").append(d.world()).append(" ").append((int)d.x()).append(" ").append((int)d.y()).append(" ").append((int)d.z()).append(" · ").append(d.cause());}b.append("\n§7Visitar: /profile ").append(name).append(" death <n>");}List<String> deleted=homes.deleted(id);if(!deleted.isEmpty())b.append("\n\n§6Homes eliminados §f").append(deleted.size()).append(" §7(recuperables)");if(!deleted.isEmpty()){for(String key:deleted)b.append("\n§f").append(key).append(" §8").append(homes.deletedName(id,key));b.append("\n§7Visitar eliminado: /profile ").append(name).append(" deleted <id>");};}
  ActionButton left=ActionButton.builder(Component.text(other?"Inspeccionar correo":"Abrir correo")).action(DialogAction.customClick((r,a)->{if(a instanceof Player pl){if(other){if(pl.hasPermission("mando.mail.inspect")){audit.log(pl.getName(),name,"MAIL_INSPECT","desde profile");openInbox(pl,id,true);}}else openInbox(pl,id,false);}},ClickCallback.Options.builder().uses(1).build())).build();
  ActionButton right=ActionButton.builder(Component.text(other?"Cerrar":"Abrir Homes")).action(DialogAction.customClick((r,a)->{if(a instanceof Player pl&&!other)HomesMenu.open(plugin,homes,pl);},ClickCallback.Options.builder().uses(1).build())).build();
  if(!other){ActionButton tpaButton=ActionButton.builder(Component.text(!players.tpaEnabled(id)?"Activar TPA":"Desactivar TPA")).action(DialogAction.customClick((r,a)->{if(a instanceof Player pl){tpa.toggle(pl);openProfile(pl,pl.getUniqueId(),false);}},ClickCallback.Options.builder().uses(1).build())).build();viewer.showDialog(Dialog.create(x->x.empty().base(DialogBase.builder(Component.text("Perfil · "+name)).body(List.of(DialogBody.plainMessage(Component.text(b.toString())))).build()).type(DialogType.confirmation(left,tpaButton))));}else viewer.showDialog(Dialog.create(x->x.empty().base(DialogBase.builder(Component.text("Perfil · "+name)).body(List.of(DialogBody.plainMessage(Component.text(b.toString())))).build()).type(DialogType.confirmation(left,right))));}
 private double distanceKm(Player p){long cm=0;for(Statistic s:new Statistic[]{Statistic.WALK_ONE_CM,Statistic.SPRINT_ONE_CM,Statistic.SWIM_ONE_CM,Statistic.FALL_ONE_CM,Statistic.FLY_ONE_CM,Statistic.AVIATE_ONE_CM,Statistic.BOAT_ONE_CM,Statistic.MINECART_ONE_CM,Statistic.HORSE_ONE_CM})try{cm+=p.getStatistic(s);}catch(Exception ignored){}return cm/100000.0;}
 private UUID resolveKnown(String name){Player p=Bukkit.getPlayerExact(name);if(p!=null)return p.getUniqueId();OfflinePlayer o=Bukkit.getOfflinePlayer(name);return o.hasPlayedBefore()?o.getUniqueId():null;}
 private int homeLimit(Player p){if(p.hasPermission("mando.homes.unlimited"))return Integer.MAX_VALUE;int max=plugin.getConfig().getInt("homes.max",3);for(int n:new int[]{1,3,5,10})if(p.hasPermission("mando.homes."+n))max=Math.max(max,n);return max;}
 private int parse(String s){try{return Integer.parseInt(s);}catch(Exception e){return -1;}}private String shortText(String s){return s.length()>45?s.substring(0,45)+"…":s;}
 public List<String> onTabComplete(CommandSender s,Command c,String l,String[] a){if(a.length!=1)return List.of();String q=a[0].toLowerCase(Locale.ROOT);if(c.getName().equalsIgnoreCase("mail"))return List.of("inbox","read","delete","inspect","block","unblock").stream().filter(x->x.startsWith(q)).toList();return Bukkit.getOnlinePlayers().stream().map(Player::getName).filter(x->x.toLowerCase(Locale.ROOT).startsWith(q)).toList();}
}