package dev.mando;
import io.papermc.paper.dialog.Dialog;import io.papermc.paper.registry.data.dialog.DialogBase;import io.papermc.paper.registry.data.dialog.body.DialogBody;import io.papermc.paper.registry.data.dialog.type.DialogType;import net.kyori.adventure.text.Component;import net.kyori.adventure.text.event.ClickEvent;import org.bukkit.Bukkit;import org.bukkit.entity.Player;
import java.net.*;import java.net.http.*;import java.time.Duration;import java.util.regex.*;
public final class UpdateChecker {
 private final Mando plugin;private volatile String latest,url,severity;
 public UpdateChecker(Mando p){plugin=p;}
 public void check(){if(!plugin.getConfig().getBoolean("update-checker.enabled",false))return;String endpoint=plugin.getConfig().getString("update-checker.metadata-url","");if(endpoint.isBlank()||!endpoint.startsWith("https://"))return;HttpClient.newBuilder().connectTimeout(Duration.ofSeconds(5)).build().sendAsync(HttpRequest.newBuilder(URI.create(endpoint)).timeout(Duration.ofSeconds(8)).GET().build(),HttpResponse.BodyHandlers.ofString()).thenAccept(r->{if(r.statusCode()/100!=2)return;latest=find(r.body(),"version");url=find(r.body(),"url");severity=find(r.body(),"severity");if(latest!=null&&!latest.equals(plugin.getPluginMeta().getVersion()))Bukkit.getScheduler().runTask(plugin,()->{plugin.getLogger().warning("Actualización Mando disponible: "+latest+" ["+(severity==null?"normal":severity)+"]");for(Player p:Bukkit.getOnlinePlayers())if(p.hasPermission("mando.admin"))show(p);});}).exceptionally(e->null);}
 public void show(Player p){if(latest==null)return;Component c=Component.text("Instalada: "+plugin.getPluginMeta().getVersion()+"\nDisponible: "+latest+"\nSeveridad: "+(severity==null?"normal":severity));if(url!=null&&url.startsWith("https://"))c=c.append(Component.text("\n[Abrir descarga]").clickEvent(ClickEvent.openUrl(url)));final Component body=c;Dialog d=Dialog.create(b->b.empty().base(DialogBase.builder(Component.text("Mando · Actualización")).body(java.util.List.of(DialogBody.plainMessage(body))).build()).type(DialogType.notice()));p.showDialog(d);}
 private String find(String json,String key){Matcher m=Pattern.compile("\""+key+"\"\\s*:\\s*\"([^\"]+)\"").matcher(json);return m.find()?m.group(1):null;}
}
